### ISSUE TITLE
NCSU Feedback on Portal/CF Operation Master Issue

### ISSUE THREAD

**Issue by YufengXin** [AERPAW-Platform-Control/User-Feedback#1]
Here is some consolidated feedback from various members of the NC State team who have been trying to familiarize with the Portal, and exercise its capabilities to get ready for GA Ops. Most of these relate to capability that has to exist by GA - the order of the items below probably roughly correspond to urgency (from high to less high).

  Please let us know if there is any need to discuss further, or how/when you intent to handle these.  These might actually be appropriate items to add to the Phase-1 remaining tasks SoW for the budget request that is still pending.  As such, we could discuss this in Monday’s meeting.

  As a reminder, we are also hoping information will be available on Monday that will give the NC State lead team some clarity on the actual amount the budget request for the remaining Phase-1 tasks (June to September 2021) will be for, and the cumulative amount this will bring RENCI’s expenditures to by the end of September 2021.

  Regarding Monday, I personally will have a hard stop at 4:30 PM, just FYI.  Thanks.

——————————

- [ ] Regarding the overall portal, I'm still (slightly) unclear what is the relationship between the various elements in the portal. Personally, it would help a lot to have a diagram with all the important elements (users (with flags), projects, experiments, resources, operator, etc.) and their relationships (who can create and destroy what, who can recruit what, and who can see what). I guess that the whole diagram could be listed in form of bullets, but it's probably harder to follow. #3 

- [ ] The mail system (which for now seems crucial for the operation of the portal), seems to be down sometimes (for hours at a time last Thursday). #2 
- [ ] When an “AERPAW User” has multiple roles, it is not possible for the user, once logged in, to know what role (or view for what role) they are currently in, or to change roles.  (Or if it is possible, it is not obvious how to accomplish.)  Please include such menu items, or other ways of accomplishing. #4 

- [ ] There seems to be some missing functionality on the "Projects" page: each project seems to have a "Join" button, but it does not seem to do anything once pressed. I'm not sure what's supposed to do - I assume that it should allow a new user join an existing project, but doesn't seem to do the trick (the owner of the project doesn't get an email or any other notification as far as I can tell). #5 

- [ ] When listing experiments, please also show which experiments are "mine" (or I'm a part of) separate from the rest of the experiments (similar to the Projects). #6 

- [ ] When listing both Experiments and Projects, it may be a problem showing everybody's projects and experiments for everybody to see. It may be useful to make a flag both for projects and experiments that would allow a user to keep a project or experiment private. List the others (that don't care). #7 

- [ ] the testbed resources view is different for users with different powers - the view with the time line (available for the operators) still does not help (at this time), as the testbed resources are not scheduled through the portal at this time. #8 

- [ ] please remove the emulab nodes from the resources; or confirm that anybody with an “Ops” role may do so. #9 

- [ ] the resources filter seems to not work (tried to filter by fixed nodes, but portable nodes still showed up) #10 

- [ ] it seems that users that lose all their priviledges (including AERPAW user), can still edit experiments they are part of and initiate development in them. #11 

- [ ] please add relevant links to the documentation for the portal - I think that this is a GA requirement.  Links should explicitly be added for: (i) AERPAW main website, aerpaw.org, (ii) AERPAW wiki (link is on aerpaw.org).  Please include links in Portal front page, maybe in a section just above current “Operator Tools”.  Please front the links with the text “User manuals, tutorials, and other relevant documentation can be found at the following links; please refer to relevant instructions before attempting to use this Portal." #12 

- [ ] please add a link to the acceptable use policy (Ismail or Lavanya will provide the link URL once it's posted) - this is a GA requirement if I'm not wrong. #13 

- [ ] it would be nice to have contextual help throughout the portal. A relatively unobtrusive way to provide it is to have a small question mark or similar link next to each field and button with a small pop-up explaining what's supposed to go in the field or what would happen upon pressing the button. #14

**Comment by YufengXin** [comment]
Done at the end of the phase 1 and deployed in the running portal.
